on:
  push:
    branches:
      - main
      - feature/backend
  pull_request:
    branches:
      - main

jobs:
  build_test_backend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.2"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Build Backend
        run: |
          cd backend
          python -m py_compile main.py
          python -m py_compile LicensePlateRecognitionAPI.py
          python -m py_compile ticketsDb_utils.py
          python -m py_compile userDb_utils.py
      - name: Run tests
        env:
          OKTA_URL: ${{ secrets.OKTA_URL }}
          OKTA_CLIENT_ID: ${{ secrets.OKTA_CLIENT_ID }}
          OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
          USERS_DB: ${{ secrets.USERS_DB }}
          TICKETS_DB: ${{ secrets.TICKETS_DB }}
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
          OFFICERS: ${{ secrets.OFFICERS }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          cd backend
          pytest tests/ --cov=. --cov-report html
      - name: Publish Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report_${{ github.sha }}.zip
          path: tests/htmlcov/
      - name: Security Check
        run: |
          cd backend
          pip-audit > backend-security-report.txt
        continue-on-error: true
      - name: Publish Security Report
        uses: actions/upload-artifact@v4
        with:
          name: backend-security-report_${{ github.sha }}.txt
          path: backend/backend-security-report.txt

  build_backend_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Backend Docker Image
        run: |
          docker build -t backend .
          docker save backend -o backend_docker_image.tar
      - name: Publish Backend Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: backend-docker-image-${{ github.sha }}.tar
          path: backend/backend_docker_image.tar

  build_test_frontend:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "24.13.0"
      - name: Install dependencies
        run: |
          cd frontend/react-app
          npm install
      - name: Build Frontend
        run: |
          cd frontend/react-app
          npm run build
      - name: Run tests
        run: |
          cd frontend/react-app
          npm run test
      - name: Frontend Coverage
        run: |
          cd frontend/react-app
          npm run test:coverage
      - name: Publish Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report_${{ github.sha }}.zip
          path: frontend/react-app/coverage/
      - name: Security Check
        run: |
          cd frontend/react-app
          npm audit --audit-level=high --json > npm-audit-report.json
        continue-on-error: true
      - name: Publish Security Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-security-report_${{ github.sha }}.json
          path: frontend/react-app/npm-audit-report.json

  build_frontend_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t frontend .
          docker save frontend -o frontend_docker_image.tar
      - name: Publish Frontend Docker Image
        uses: actions/upload-artifact@v4
        with:
          name: frontend-docker-image_${{ github.sha }}.tar
          path: frontend/frontend_docker_image.tar
